# Generated by Django 3.2.9 on 2021-11-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('record', models.CharField(max_length=255, verbose_name='Record')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('best_song', models.CharField(max_length=255, verbose_name='Best Song')),
            ],
            options={
                'verbose_name': 'Persons',
                'verbose_name_plural': 'Person',
            },
        ),
    ]
