# Generated by Django 3.2.9 on 2021-11-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
