# Generated by Django 3.2.9 on 2021-11-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_persons_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='data',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
