# Generated by Django 3.2.9 on 2021-11-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_persons_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='actions',
            field=models.BooleanField(default=True, verbose_name='Action'),
        ),
    ]
